version: '2'

services:
  db:
    image: mariadb
    container_name: ds-db
    environment:
      - MYSQL_ROOT_PASSWORD=123132123
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=web
      - MYSQL_PASSWORD=123456
    volumes:
      - ./docker/mysql/build/:/docker-entrypoint-initdb.d
      - ./docker/mysql/log/:/var/log/mysql
      - ./docker/mysql/data/:/var/lib/mysql
    networks:
      - back-tier
    restart: always

  pmd:
    image: phpmyadmin/phpmyadmin
    container_name: ds-phpmyadmin
    ports:
      - "8000:80"
    networks:
      - back-tier
    restart: always

  memcached:
    image: memcached
    container_name: ds-memcached
    ports:
      - "11211:11211"
    networks:
      - back-tier
    restart: always

  app:
      build: ./
      container_name: ds-php7-fpm
      expose:
          - "9000"
      volumes:
          - ./:/var/www/html/
      networks:
        - back-tier
      restart: always
      environment:
        ENABLE_ENV_FILE: 1
        ENABLE_LOCALCONF: 1
        API_TOKEN: "============ GitHub Api Token ==========="

  nginx:
      build: ./docker/nginx
      container_name: ds-nginx
      ports:
          - "80:80"
      volumes_from:
          - app
      networks:
        - back-tier
      restart: always

volumes:
  db-data:
      driver: local

networks:
  back-tier:
      driver: bridge
